### ISSUE TITLE
Make it installable in Pypi or similar

### ISSUE THREAD

**Issue by Nebelhom** [Nebelhom/SlideShow4RaspberryPi#19]

**Comment by Nebelhom** [comment]
When opening a new test environment using `virtualenv` where kivy is not installed and I used setup.py according to https://github.com/Nebelhom/SlideShow4RaspberryPi/tree/issue_19_create_setuppy

Investigate and checkout if it is my fault, an issue with virtualenv or an issue with kivy

`(test) pi@raspberrypi:~/test $ python setup.py sdist bdist_wheel
running sdist
running egg_info
creating slideshow_Nebelhom.egg-info
writing slideshow_Nebelhom.egg-info/PKG-INFO
writing dependency_links to slideshow_Nebelhom.egg-info/dependency_links.txt
writing requirements to slideshow_Nebelhom.egg-info/requires.txt
writing top-level names to slideshow_Nebelhom.egg-info/top_level.txt
writing manifest file 'slideshow_Nebelhom.egg-info/SOURCES.txt'
reading manifest file 'slideshow_Nebelhom.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'slideshow_Nebelhom.egg-info/SOURCES.txt'
running check
creating slideshow-Nebelhom-0.0.1
creating slideshow-Nebelhom-0.0.1/slideshow
creating slideshow-Nebelhom-0.0.1/slideshow_Nebelhom.egg-info
copying files to slideshow-Nebelhom-0.0.1...
copying MANIFEST.in -> slideshow-Nebelhom-0.0.1
copying README.md -> slideshow-Nebelhom-0.0.1
copying requirements.txt -> slideshow-Nebelhom-0.0.1
copying setup.py -> slideshow-Nebelhom-0.0.1
copying slideshow/__init__.py -> slideshow-Nebelhom-0.0.1/slideshow
copying slideshow/helper_func.py -> slideshow-Nebelhom-0.0.1/slideshow
copying slideshow/main.py -> slideshow-Nebelhom-0.0.1/slideshow
copying slideshow_Nebelhom.egg-info/PKG-INFO -> slideshow-Nebelhom-0.0.1/slideshow_Nebelhom.egg-info
copying slideshow_Nebelhom.egg-info/SOURCES.txt -> slideshow-Nebelhom-0.0.1/slideshow_Nebelhom.egg-info
copying slideshow_Nebelhom.egg-info/dependency_links.txt -> slideshow-Nebelhom-0.0.1/slideshow_Nebelhom.egg-info
copying slideshow_Nebelhom.egg-info/requires.txt -> slideshow-Nebelhom-0.0.1/slideshow_Nebelhom.egg-info
copying slideshow_Nebelhom.egg-info/top_level.txt -> slideshow-Nebelhom-0.0.1/slideshow_Nebelhom.egg-info
Writing slideshow-Nebelhom-0.0.1/setup.cfg
creating dist
Creating tar archive
removing 'slideshow-Nebelhom-0.0.1' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/slideshow
copying slideshow/__init__.py -> build/lib/slideshow
copying slideshow/main.py -> build/lib/slideshow
copying slideshow/helper_func.py -> build/lib/slideshow
installing to build/bdist.linux-armv7l/wheel
running install
running install_lib
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/wheel
creating build/bdist.linux-armv7l/wheel/slideshow
copying build/lib/slideshow/__init__.py -> build/bdist.linux-armv7l/wheel/slideshow
copying build/lib/slideshow/main.py -> build/bdist.linux-armv7l/wheel/slideshow
copying build/lib/slideshow/helper_func.py -> build/bdist.linux-armv7l/wheel/slideshow
running install_egg_info
Copying slideshow_Nebelhom.egg-info to build/bdist.linux-armv7l/wheel/slideshow_Nebelhom-0.0.1-py3.7.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-armv7l/wheel/slideshow_Nebelhom-0.0.1.dist-info/WHEEL
creating 'dist/slideshow_Nebelhom-0.0.1-py3-none-any.whl' and adding 'build/bdist.linux-armv7l/wheel' to it
adding 'slideshow/__init__.py'
adding 'slideshow/helper_func.py'
adding 'slideshow/main.py'
adding 'slideshow_Nebelhom-0.0.1.dist-info/LICENSE'
adding 'slideshow_Nebelhom-0.0.1.dist-info/METADATA'
adding 'slideshow_Nebelhom-0.0.1.dist-info/WHEEL'
adding 'slideshow_Nebelhom-0.0.1.dist-info/top_level.txt'
adding 'slideshow_Nebelhom-0.0.1.dist-info/RECORD'
removing build/bdist.linux-armv7l/wheel
(test) pi@raspberrypi:~/test $ python setup.py install
running install
running bdist_egg
running egg_info
writing slideshow_Nebelhom.egg-info/PKG-INFO
writing dependency_links to slideshow_Nebelhom.egg-info/dependency_links.txt
writing requirements to slideshow_Nebelhom.egg-info/requires.txt
writing top-level names to slideshow_Nebelhom.egg-info/top_level.txt
reading manifest file 'slideshow_Nebelhom.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'slideshow_Nebelhom.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/slideshow
copying build/lib/slideshow/__init__.py -> build/bdist.linux-armv7l/egg/slideshow
copying build/lib/slideshow/main.py -> build/bdist.linux-armv7l/egg/slideshow
copying build/lib/slideshow/helper_func.py -> build/bdist.linux-armv7l/egg/slideshow
byte-compiling build/bdist.linux-armv7l/egg/slideshow/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/slideshow/main.py to main.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/slideshow/helper_func.py to helper_func.cpython-37.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying slideshow_Nebelhom.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying slideshow_Nebelhom.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying slideshow_Nebelhom.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying slideshow_Nebelhom.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying slideshow_Nebelhom.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/slideshow_Nebelhom-0.0.1-py3.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing slideshow_Nebelhom-0.0.1-py3.7.egg
Copying slideshow_Nebelhom-0.0.1-py3.7.egg to /home/pi/test/lib/python3.7/site-packages
Adding slideshow-Nebelhom 0.0.1 to easy-install.pth file

Installed /home/pi/test/lib/python3.7/site-packages/slideshow_Nebelhom-0.0.1-py3.7.egg
Processing dependencies for slideshow-Nebelhom==0.0.1
Searching for kivy>=2.0.0
Reading https://pypi.org/simple/kivy/
Downloading https://files.pythonhosted.org/packages/12/96/091ddacafb84dd18555a32d860dbfaf9c806147aa30c6f3c8b93cb7bab97/Kivy-2.0.0.tar.gz#sha256=d25e44eb44e43762b2fd0c5874e51954e0f1181fd9800d8a6756be6d084812d8
Best match: Kivy 2.0.0
Processing Kivy-2.0.0.tar.gz
Writing /tmp/easy_install-vx5dolqo/Kivy-2.0.0/setup.cfg
Running Kivy-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vx5dolqo/Kivy-2.0.0/egg-dist-tmp-gvhom4kk
[ERROR  ] Error while activating FileHandler logger
Traceback (most recent call last):
  File "/tmp/easy_install-vx5dolqo/Kivy-2.0.0/kivy/__init__.py", line 367, in <module>
    'config=', 'debug', 'dpi='])
  File "/usr/lib/python3.7/getopt.py", line 95, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/usr/lib/python3.7/getopt.py", line 195, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/usr/lib/python3.7/getopt.py", line 211, in short_has_arg
    raise GetoptError(_('option -%s not recognized') % opt, opt)
getopt.GetoptError: option -q not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/easy_install-vx5dolqo/Kivy-2.0.0/kivy/logger.py", line 250, in emit
    self._configure()
  File "/tmp/easy_install-vx5dolqo/Kivy-2.0.0/kivy/logger.py", line 223, in _configure
    FileHandler.fd = open(filename, 'w', encoding=FileHandler.encoding)
  File "/home/pi/test/lib/python3.7/site-packages/setuptools/sandbox.py", line 422, in _open
    self._violation("open", path, mode, *args, **kw)
  File "/home/pi/test/lib/python3.7/site-packages/setuptools/sandbox.py", line 411, in _violation
    raise SandboxViolation(operation, args, kw)
setuptools.sandbox.SandboxViolation: SandboxViolation: open('/home/pi/.kivy/logs/kivy_20-12-23_3.txt', 'w') {'encoding': 'utf-8'}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

[ERROR  ] [Core        ] option -q not recognized
Kivy Usage: setup.py [OPTION...]::

            Set KIVY_NO_ARGS=1 in your environment or before you import Kivy to
            disable Kivy's argument parser.

        -h, --help
            Prints this help message.
        -d, --debug
            Shows debug log.
        -a, --auto-fullscreen
            Force 'auto' fullscreen mode (no resolution change).
            Uses your display's resolution. This is most likely what you want.
        -c, --config section:key[:value]
            Set a custom [section] key=value in the configuration object.
        -f, --fullscreen
            Force running in fullscreen mode.
        -k, --fake-fullscreen
            Force 'fake' fullscreen mode (no window border/decoration).
            Uses the resolution specified by width and height in your config.
        -w, --windowed
            Force running in a window.
        -p, --provider id:provider[,options]
            Add an input provider (eg: ccvtable1:tuio,192.168.0.1:3333).
        -m mod, --module=mod
            Activate a module (use "list" to get a list of available modules).
        -r, --rotation
            Rotate the window's contents (0, 90, 180, 270).
        -s, --save
            Save current Kivy configuration.
        --size=640x480
            Size of window geometry.
        --dpi=96
            Manually overload the Window DPI (for testing only.)
    
 error: Setup script exited with 2
`
